apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-page
        image: kubedevio/web-page:green
        ports:
          - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: web-page-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort