swagger: "2.0"
info:
  description: "Kubernetes Self Healing, application health check, ready to serve and resources limits"
  version: "1.0.0"
  title: "kubernetes-selfhealing-healthcheck-resourceslimits"
  contact:
    email: "josemarsilva@yahoo.com.br"
paths:

  /:
    get:
      description: "Home page"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "Home Page - node-express-swagger-liveness-readiness-startup-probes"

  /health-check:
    get:
      description: "Probe if application is running?"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "_health-check_ responds: Yes, application is running\nExample#1: OK - GET /health-check"

  /ready-to-serve:
    get:
      description: "Probe if application is ready to serve?"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "_ready-to-serve_ responds: Yes, application ready to serve\nExample#1: OK - GET /ready-to-serve"

  /get-delayed/{seconds}:
    get:
      description: "Delay an amount of time and respond request"
      produces:
      - "text/plain"
      parameters:
      - name: "seconds"
        in: "path"
        description: "seconds amount of time in seconds"
        required: false
        type: "number"
      responses:
        "200":
          description: "_get-delayed_ delay an amount of time and respond request"

  /when-will-you-be-ready:
    get:
      description: "When will application be ready to serve?"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "_when-will-you-be-ready_ responds: current datetime and readiness datetime. \nExample#1:  OK - {\"isHealthCheck\": True, \"is_ready_to_serve\": True}"

  /set-unhealth:
    put:
      description: "Set application in a **NOT running** mode"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "_set-unhealth_ set application in a **NOT running** mode"

  /set-health:
    put:
      description: "Set application in a **running** mode"
      produces:
      - "text/plain"
      responses:
        "200":
          description: "_set-health_ set application in a **running** mode"

  /set-unready-for/{seconds}:
    put:
      description: "Set application in a **NOT ready-to-serve** mode for a time in seconds"
      produces:
      - "text/plain"
      parameters:
      - name: "seconds"
        in: "path"
        description: "seconds amount of time in seconds"
        required: false
        type: "number"
      responses:
        "200":
          description: "_set-unready-for_ set application in a **NOT ready-to-serve** mode for a time in seconds"

  /stress/lifespan/{lifespan}/deathspan/{deathspan}/iterations/{iterations}:
    put:
      description: "Use Nodehog stress tools used to stress CPU"
      produces:
      - "text/plain"
      parameters:
      - name: "lifespan"
        in: "path"
        description: "lifespan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "deathspan"
        in: "path"
        description: "deathspan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "iterations"
        in: "path"
        description: "iterations amount of interations integer number"
        required: true
        type: "number"
      responses:
        "200":
          description: "_stress_ stress CPU using Nodehog tools"
