swagger: "2.0"
info:
  description: "Kubernetes Self Healing, application health check, ready to serve and resources limits"
  version: "1.0.0"
  title: "kubernetes-selfhealing-healthcheck-resourceslimits"
  contact:
    email: "josemarsilva@yahoo.com.br"
paths:
  /health-check:
    get:
      description: "health-check: Is application is running?"
      produces:
      - "application/json"
      parameters:
      responses:
        "200":
          description: "health-check: Yes, application is running"
  /ready-to-serve:
    get:
      description: "ready-to-serve: Is application ready to serve?"
      produces:
      - "application/json"
      parameters:
      responses:
        "200":
          description: "ready-to-serve: Yes, application ready to serve"

