swagger: "2.0"
info:
  description: "Kubernetes Self Healing, application health check, ready to serve and resources limits"
  version: "1.0.0"
  title: "kubernetes-selfhealing-healthcheck-resourceslimits"
  contact:
    email: "josemarsilva@yahoo.com.br"
paths:
  /health-check:
    get:
      description: "Is application is running?"
      produces:
      - "application/json"
      responses:
        "200":
          description: "health-check: Yes, application is running"
  /ready-to-serve:
    get:
      description: "Is application ready to serve?"
      produces:
      - "application/json"
      responses:
        "200":
          description: "ready-to-serve: Yes, application ready to serve"
  /stress/lifespan/{lifespan}/deathspan/{deathspan}/iterations/{iterations}:
    put:
      description: "Use Nodehog stress tools used to stress CPU"
      produces:
      - "application/json"
      parameters:
      - name: "lifespan"
        in: "path"
        description: "lifespan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "deathspan"
        in: "path"
        description: "deathspan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "iterations"
        in: "path"
        description: "iterations amount of interations integer number"
        required: true
        type: "number"
      responses:
        "200":
          description: "health-check: Yes, application is running"
  /unhealth:
    put:
      description: "unhealth: Put application in a **NOT running** mode"
      produces:
      - "application/json"
      responses:
        "200":
          description: "unhealth: Put application in a **NOT running** mode"
  /unready-for/{seconds}:
    put:
      description: "unready-for: Put application in a **NOT ready-to-serve** mode for a time in seconds"
      produces:
      - "application/json"
      parameters:
      - name: "seconds"
        in: "path"
        description: "seconds amount of time in seconds"
        required: true
        type: "number"
      responses:
        "200":
          description: "unready-for: Put application in a **NOT ready-to-serve** mode for a time in seconds"

