# #############################################################################
# ConfigMap configmap-prometheus-server-conf-py-k8s-prometheus-exporter
# #############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-prometheus-server-conf-py-k8s-prometheus-exporter
  # namespace: monitoring
  labels:
    name: prometheus-server-conf-py-k8s-prometheus-exporter
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
      - job_name: py-k8s-prometheus-exporter
        static_configs:
          - targets: ["svc-py-k8s-prometheus-exporter:9000"]
            labels:
              subsystem: "py-k8s-prometheus-exporter"
