apiVersion: v1
kind: ConfigMap
metadata:
  name: py-k8s-prometheus-server-conf
  labels:
    name: py-k8s-prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/prometheus.rules

    scrape_configs:
      - job_name: py-k8s-prometheus-exporter
        static_configs:
          - targets: ["py-k8s-prometheus-exporter-clusterip:9000"]
            labels:
              subsystem: "py-k8s-prometheus"
 