# #############################################################################
# Deployment deploy-py-k8s-prometheus-exporter
# #############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-py-k8s-prometheus-exporter
#  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: py-k8s-prometheus-exporter
  template:
    metadata:
      labels:
        app: py-k8s-prometheus-exporter
    spec:
      containers:
      - name: py-k8s-prometheus-exporter
        image: josemarsilva/py-k8s-prometheus-exporter:latest
        ports:
          - containerPort: 9000

---

# #############################################################################
# Service svc-py-k8s-prometheus-exporter
# #############################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-py-k8s-prometheus-exporter
  # namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: py-k8s-prometheus-exporter

---

# #############################################################################
# Service svc-nodeport-py-k8s-prometheus-exporter
# #############################################################################
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-py-k8s-prometheus-exporter
#  namespace: monitoring
spec:
  selector:
    app: py-k8s-prometheus-exporter
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30095
  type: NodePort
