# #############################################################################
# Deployment mongodb
# #############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd


---

# #############################################################################
# Service mongodb
# #############################################################################
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP


---

# #############################################################################
# Deployment web-app-py-flask
# #############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-py-flask
spec:
  selector:
    matchLabels:
      app: web-app-py-flask
  template:
    metadata:
      labels:
        app: web-app-py-flask
    spec:
      containers:
      - name: web-app-py-flask
        image: josemarsilva/rotten-potatoes:v1
        ports:
          - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopwd


---

# #############################################################################
# Service web-app-py-flask
# #############################################################################
apiVersion: v1
kind: Service
metadata:
  name: web-app-py-flask
spec:
  selector:
    app: web-app-py-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30001
  type: NodePort