swagger: "2.0"
info:
  description: "Kubernetes Self Healing, application health check, ready to serve and resources limits"
  version: "1.0.0"
  title: "kubernetes-selfhealing-healthcheck-resourceslimits"
  contact:
    email: "josemarsilva@yahoo.com.br"
paths:
  /health-check:
    get:
      description: "health-check: Is application is running?"
      produces:
      - "application/json"
      responses:
        "200":
          description: "health-check: Yes, application is running"
  /ready-to-serve:
    get:
      description: "ready-to-serve: Is application ready to serve?"
      produces:
      - "application/json"
      responses:
        "200":
          description: "ready-to-serve: Yes, application ready to serve"
  /stress/lifespan/{lifespan}/deathspan/{deathspan}/iterations/{iterations}:
    get:
      description: "stress: start working stressing CPU"
      produces:
      - "application/json"
      parameters:
      - name: "lifespan"
        in: "path"
        description: "lifespan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "deathspan"
        in: "path"
        description: "deathspan amount of time in milliseconds"
        required: true
        type: "number"
      - name: "iterations"
        in: "path"
        description: "iterations amount of interations integer number"
        required: true
        type: "number"
      responses:
        "200":
          description: "health-check: Yes, application is running"

