version: '3'

services:

  app:
    build: .
    volumes:
      - .:/go/src
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
    volumes:
      - "../../volume/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"